### ISSUE TITLE
any way to edit layout string to generate a halloween map?

### ISSUE THREAD

**Issue by moonblock64** [OndrejNepozitek/PlateUpMods#11]
Hello,

I noticed the 4th and 5th character in the layout string determines the map type (ow/oz/ox/oy). Is there any character combination that could force the layout to be halloween themed? Or would I need to wait until its implemented into the layout editor?

thanks in advance

**Comment by OndrejNepozitek** [comment]
Hello!
Unfortunately, the support for Halloween maps will probably also require an update of the mod itself so there is currently no way to do this by only changing the output string of the editor.

**Comment by shiftthedev** [comment]
Isn't possible to make a small Halloween update where all seeds use Halloween location similar to how the game is doing?

**Comment by OndrejNepozitek** [comment]
Hello, I'm currently working on an updated version of the mod and the online editor where you'll be able to use the Halloween setting. Should be out soon I hope.

**Comment by shiftthedev** [comment]
Awesome thanks!

**Comment by OndrejNepozitek** [comment]
Hey, I released version 1.0.1 of Kitchen Designer now. You can find it here: https://kitchen-designer-v101--plate-up-tools.netlify.app/kitchen-designer/how-to-install It's now deployed to a staging domain until at least some verify that it works okay. That domain also contains an updated editor where you can pick the Halloween setting. Please let me know if you have any problems, or if you tried it and it works correctly.

**Comment by shiftthedev** [comment]
Tested it with 3 different Halloween themed custom maps and all worked fine. no errors on console. exiting mid game and resuming working fine also. thanks for the update.

**Comment by OndrejNepozitek** [comment]
Great, thanks for the report.
