### ISSUE TITLE
Failed to decorate dining room error

### ISSUE THREAD

**Issue by THED4RKM4RIO** [OndrejNepozitek/PlateUpMods#14]
I made a few interesting maps but i can't load it in. the mod tells me that it failed and i need to check the console log. i check the console log and it tells me that it has attempted 100 times at decorating the dining room and failed. "Failed to decorate dining room"

**Comment by THED4RKM4RIO** [comment]
here are the maps i tried making. 
https://plateuptools.com/kitchen-designer/view/2LTIwNDU4MDA4MTA6MDoxLDM7MiwyOzMsMToxOSw2OjMuMSwyLjEsMy4xLDIuMSwzLjEsMi4yLDMuMSwyLjEsMy4xLDIuMSwzLjIsMi4xLDMuMSwyLjEsMy4xLDIuMiwzLjEsMi4xLDMuMSwyLjEsMy4yLDIuMSwzLjEsMi4xLDMuMSwyLjIsMy4xLDIuMSwzLjEsMi4xLDMuMiwyLjEsMy4xLDIuMSwzLjEsMi4yLDMuMSwyLjEsMy4xLDIuMSwzLjIsMi4xLDMuMSwyLjEsMy4xLDIuMSwxLjYwOjEsLTEsMSwwLDM7OCwwLDksMCwxOzcsMCw4LDAsMTs2LDAsNywwLDE7MiwwLDMsMCwxOzMsMCw0LDAsMTs0LDAsNSwwLDE7NSwwLDYsMCwxOzEsMCwyLDAsMTswLDAsMSwwLDE7MCwxLDAsMiwxOzAsMiwwLDMsMTswLDQsMCw1LDE7MCw1LDEsNSwxOzEsNSwyLDUsMTs2LDUsNyw1LDE7Nyw1LDgsNSwxOzgsMSw4LDIsMTs4LDAsOCwxLDE7NywxLDgsMSwxOzcsMCw3LDEsMTs2LDEsNywxLDE7NSwxLDYsMSwxOzMsMSw0LDEsMTs0LDAsNCwxLDE7NiwwLDYsMSwxOzUsMCw1LDEsMTswLDEsMSwxLDE7MiwxLDMsMSwxOzMsMCwzLDEsMTsxLDAsMSwxLDE7MCwwLDAsMSwxOzEsMSwyLDEsMTsyLDAsMiwxLDE7MCwyLDEsMiwxOzAsMywxLDMsMTswLDMsMCw0LDE7MCw0LDEsNCwxOzEsNCwxLDUsMTsyLDQsMiw1LDE7Myw1LDQsNSwxOzYsNCw3LDQsMTs3LDQsNyw1LDE7OCw0LDgsNSwxOzcsNCw4LDQsMTs1LDUsNiw1LDE7NCw0LDQsNSwxOzMsNCwzLDUsMTsyLDUsMyw1LDE7NCw1LDUsNSwxOzUsNCw1LDUsMTs2LDQsNiw1LDE7NywzLDgsMywxOzcsMiw4LDIsMTs2LDIsNywyLDE7NiwxLDYsMiwxOzUsMSw1LDIsMTs0LDEsNSwxLDE7NCwxLDQsMiwxOzMsMSwzLDIsMTsyLDEsMiwyLDE7MSwxLDEsMiwxOzEsMiwyLDIsMTsyLDMsMiw0LDE7MiwyLDIsMywxOzEsNCwyLDQsMTsyLDQsMyw0LDE7Myw0LDQsNCwxOzUsNCw2LDQsMTs2LDMsNiw0LDE7NywzLDcsNCwxOzYsMyw3LDMsMTs3LDIsNywzLDE7OCwxLDksMSwxOzgsMiw5LDIsMTs4LDMsOSwzLDE7OCwzLDgsNCwxOzgsNSw5LDUsMTs4LDQsOSw0LDE7OCwyLDgsMywxOzcsMSw3LDIsMTs2LDIsNiwzLDE7NSwzLDYsMywxOzUsMiw1LDMsMTs1LDMsNSw0LDE7NCw0LDUsNCwxOzQsMyw1LDMsMTs0LDIsNCwzLDE7NCwzLDQsNCwxOzMsMyw0LDMsMTszLDMsMyw0LDE7MiwzLDMsMywxOzIsMiwzLDIsMTsxLDMsMiwzLDE7MSwzLDEsNCwxOzEsMiwxLDMsMTszLDIsMywzLDE7NSwyLDYsMiwxOzQsMiw1LDIsMTszLDIsNCwyLDE6

**Comment by THED4RKM4RIO** [comment]
https://plateuptools.com/kitchen-designer/view/2LTIwNDU4MDA4MTA6MDoxLDM7MiwyOzMsMToxOSw2OjMuMSwyLjEsMy4xLDIuMSwzLjEsMi4yLDMuMSwyLjEsMy4xLDIuMSwzLjIsMi4xLDMuMSwyLjEsMy4xLDIuMiwzLjEsMi4xLDMuMSwyLjEsMy4yLDIuMSwzLjEsMi4xLDMuMSwyLjIsMy4xLDIuMSwzLjEsMi4xLDMuMiwyLjEsMy4xLDIuMSwzLjEsMi4yLDMuMSwyLjEsMy4xLDIuMSwzLjIsMi4xLDMuMSwyLjEsMy4xLDIuMSwxLjYwOjEsLTEsMSwwLDM6

**Comment by THED4RKM4RIO** [comment]
https://plateuptools.com/kitchen-designer/view/2MTU0OTM4NzA4OjIwMDI4NzYyOTU6MiwyOzMsMjs0LDI7NSwyOzEsMzs2LDI7NywyOzgsMjs5LDI7MTAsMjsxMSwyOzEyLDI7MTMsMjozNCw5OjIuMTgsNi40LDIuMiw2LjEsMi4yLDYuNCwyLjIsNi4xLDIuMiw2LjQsMi4yLDYuMSwyLjIsNi45LDMuMjAsNy43LDMuMiw3LjcsMy4xOCw4LjksNC4yMCw5LjUsNC40LDkuNSw0LjQsOS41LDQuNCw5LjUsNC4yLDkuOSw1LjE4LDExLjMsNS4zLDEwLjMsMTEuMiw1LjIsMTIuMSw1LjIsMTAuMiwxMS4xLDUuMiwxMi4zLDUuMiwxMC4xLDUuMiwxMi41LDUuMywxMi43LDUuMSwxMi45LDEuMjAsMTMuNywxLjIsMTMuNywxLjE4OjAsLTEsMCwwLDM7MSwwLDIsMCwxOzgsMSw4LDIsMTsxMSwwLDEyLDAsMTsxOCwwLDE5LDAsMTsyMSwwLDIyLDAsMTsyMiw1LDIyLDYsMTsyNiwwLDI3LDAsMTszMCwxLDMwLDIsMTs1LDAsNiwwLDE7MTIsMCwxMywwLDE7MTksMCwyMCwwLDE7MjQsMCwyNSwwLDE7MjcsMiwyOCwyLDI7MjcsMSwyOCwxLDI7MjcsMCwyOCwwLDE6

**Comment by THED4RKM4RIO** [comment]
https://plateuptools.com/kitchen-designer/view/2LTIwNDU4MDA4MTA6MjAwMjg3NjI5NToyLDI7MSwzOjM0LDk6Mi4xOCwxLjEsMC4zLDIuMiwwLjEsMi4yLDEuMSwwLjMsMi4yLDAuMSwyLjIsMS4xLDAuMywyLjIsMC4xLDIuMiwxLjEsMC44LDIuMjAsMC43LDIuMiwwLjcsMi4xOCwxLjEsMC44LDIuMjAsMC41LDIuNCwwLjUsMi40LDAuNSwyLjQsMC41LDIuMiwxLjEsMC44LDIuMTgsMC4zLDIuMywwLjUsMi4yLDAuMSwyLjIsMC4zLDIuMiwwLjMsMi4yLDAuMSwyLjIsMC41LDIuMiwxLjEsMC43LDIuMiwwLjgsMS4yMCwwLjcsMS4yLDAuNywxLjE4OjAsLTEsMCwwLDM7MzAsMSwzMCwyLDI7MzEsMSwzMSwyLDI7MSw2LDIsNiwxOzUsMCw2LDAsMTsxLDAsMiwwLDE7MTEsMCwxMiwwLDE7MTIsMCwxMywwLDE7MTgsMCwxOSwwLDE7MTksMCwyMCwwLDE7MjUsMCwyNiwwLDE7MjYsMCwyNywwLDE7MjcsMCwyOCwwLDE6

**Comment by OndrejNepozitek** [comment]
The game needs enough space to decorate a dining room with tables. If there is not enough space, the process fails. This has nothing to do with Kitchen Designer - it is just how the game is designed.

I do not plan to change how the game works internally, so you need to design your layout in a way that the game can place all the necessary stuff inside dining rooms and kitchens.
