### ISSUE TITLE
When i use the mod, my save gets deleted and i get an error

### ISSUE THREAD

**Issue by Qyubij** [OndrejNepozitek/PlateUpMods#16]
not sure why this is happening, first time using this mod and BepInEx, here is the error

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000031 (from typeref, class/assembly Kitchen.Seed, Kitchen.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
Stack trace:
System.Reflection.MonoMethodInfo.GetMethodInfo (System.IntPtr handle) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Reflection.MonoMethod.GetPseudoCustomAttributes () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.MonoCustomAttrs.GetPseudoCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Boolean inherit) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Reflection.MonoMethod.GetCustomAttributes (System.Boolean inherit) (at <695d1cc93cca45069c528c15c9fdd749>:0)
HarmonyLib.PatchTools+<>c__DisplayClass2_0.<GetPatchMethod>b__0 (System.Reflection.MethodInfo m) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
HarmonyLib.PatchTools.GetPatchMethod (System.Type patchType, System.String attributeName) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor..ctor (HarmonyLib.Harmony instance, System.Type type, System.Boolean allowUnannotatedType) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor..ctor (HarmonyLib.Harmony instance, System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.CreateClassProcessor (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
ONe.KitchenDesigner.KitchenDesigner.Awake () (at <3547f65d496e448f876493694157669a>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()

**Comment by OndrejNepozitek** [comment]
Hello, do you have the newest Turkey Day update? Because if so, the update broke the Kitchen Designer mod. I hope to release a new version soon.

**Comment by StevenAEdwards** [comment]
Hey! I'm having the same issue he is and I am on the turkey day update v1.1.1 I saw his comment and wanted to clarify. Thanks for all you do!

**Comment by Qyubij** [comment]
> Hello, do you have the newest Turkey Day update? Because if so, the update broke the Kitchen Designer mod. I hope to release a new version soon.

yes i do hqve the newest update, that's probably the reason, thank you I hope to get the new version soon, could i ask when it will be released?

**Comment by OndrejNepozitek** [comment]
Hello, I just released a new version. You can go here https://plateuptools.com/kitchen-designer/how-to-install and see the Migrate to a new version section at the bottom of the page.

Let me know if it works for you.

**Comment by Qyubij** [comment]
Ok i will try, as currently in school now so probably in 8 and a half hours i will test it

**Comment by Qyubij** [comment]
> Hello, I just released a new version. You can go here https://plateuptools.com/kitchen-designer/how-to-install and see the Migrate to a new version section at the bottom of the page.
> 
> Let me know if it works for you.

It works thank you

**Comment by Qyubij** [comment]
By the way in the kitchen designer editor can you scroll up, or is the space you have the space you get?

**Comment by Qyubij** [comment]
also ive just realised my cards are messed up, im getting two menu options and i also got a card called community at the start of the run, which increases my group size every few days, which obviously i don't want and is unfair, , anyway to fix this?

**Comment by OndrejNepozitek** [comment]
> By the way in the kitchen designer editor can you scroll up, or is the space you have the space you get?

You should be able to hold the middle mouse button to move the canvas

**Comment by OndrejNepozitek** [comment]
> also ive just realised my cards are messed up, im getting two menu options and i also got a card called community at the start of the run, which increases my group size every few days, which obviously i don't want and is unfair, , anyway to fix this?

I think you're playing on the new Autumn restaurant setting

**Comment by Qyubij** [comment]
oh i thought that was a mod apparently not ty

> > also ive just realised my cards are messed up, im getting two menu options and i also got a card called community at the start of the run, which increases my group size every few days, which obviously i don't want and is unfair, , anyway to fix this?
> 
> I think you're playing on the new Autumn restaurant setting

**Comment by Qyubij** [comment]
> > By the way in the kitchen designer editor can you scroll up, or is the space you have the space you get?
> 
> You should be able to hold the middle mouse button to move the canvas

also thank you for this,im done now thanks for all the help
