### ISSUE TITLE
iv'e downloaded everything but there is one fine that's diffrent

### ISSUE THREAD

**Issue by nobro67** [OndrejNepozitek/PlateUpMods#6]
![file](https://user-images.githubusercontent.com/116044446/196308652-d58c4e0d-2f7e-44c8-a600-918cc6479631.PNG)
 the only file that is different is the xml file not sure if that has much to do but it doesnt work without.

**Comment by nobro67** [comment]
okay i changed one thing i accidently put the Bepln file as a whole into the plateup game files instead of taking the stuff inside that file and putting it in the plateup file but now another command script has opened up, what do i do about it?

**Comment by OndrejNepozitek** [comment]
Hello, do you mean the console window that opens when you run the game with the BepInEx mod loader? If so, it is completely fine to have the window openeded.

**Comment by nobro67** [comment]
yes, the window is open but when i press F1 it doesn't open the menu and I'm not sure what to do. in the console window there are a lot of warnings but no errors.

**Comment by OndrejNepozitek** [comment]
If the console window opens but the F1 button does nothing, I suspect that you maybe installed the mods in the wrong place.

Main game folder:

![image](https://user-images.githubusercontent.com/2265359/196862312-84ed01c9-4908-4be5-bdc8-231030efdd19.png)

`<main folder>/BepInEx` folder:

![image](https://user-images.githubusercontent.com/2265359/196862341-9bc0b1f0-23f4-4045-a0f9-2a33762fb5c7.png)

`<main folder>/BepInEx/plugins` folder:

![image](https://user-images.githubusercontent.com/2265359/196862442-db6bea3a-9e6a-43a3-b632-bb20d67ac3bc.png)

**Comment by nobro67** [comment]
![br](https://user-images.githubusercontent.com/116044446/197088581-e02ffdcf-a013-4a6d-95c9-24afb129e7f1.PNG)
![bru](https://user-images.githubusercontent.com/116044446/197088590-131a9596-e4d4-4c6a-94ae-78c3e0403457.PNG)
![bruh](https://user-images.githubusercontent.com/116044446/197088596-6c92c963-4549-49a9-b865-e1a0222e7655.PNG) that's what my folders look like not sure what I did wrong the only thing different is the .xml on the configurationmanager and the folder .vs so I'm not sure what to do.

**Comment by OndrejNepozitek** [comment]
Can you maybe send me what the console logs? Another possibility is that there is some problem with the mod loader not recognizing the F1 key.

**Comment by nobro67** [comment]
okay so i found out what the problem was my keyboard F1 was set to the open the microsoft help window, so now i just need to find a way to change the key to open the mod menu or change the help window.
