### ISSUE TITLE
Cant remote play with friend

### ISSUE THREAD

**Issue by saddmemories** [OndrejNepozitek/PlateUpMods#8]
Hello, i have tested the mods Loving it! but there and issue where i couldn't remoted play to a friend if the mod installed. not sure if anyone tested it.

**Comment by OndrejNepozitek** [comment]
Hello!

I heard that the console window that automatically opens with the mod might cause issues with remote play. You can try disabling it.

Go to PlateUp\BepInEx\config\BepInEx.cfg and find the [Logging.Console] section and disable the console like this:

```
[Logging.Console]

## Enables showing a console for log output.
# Setting type: Boolean
# Default value: false
Enabled = false
```

**Comment by saddmemories** [comment]
> Hello!
> 
> I heard that the console window that automatically opens with the mod might cause issues with remote play. You can try disabling it.
> 
> Go to PlateUp\BepInEx\config\BepInEx.cfg and find the [Logging.Console] section and disable the console like this:
> 
> ```
> [Logging.Console]
> 
> ## Enables showing a console for log output.
> # Setting type: Boolean
> # Default value: false
> Enabled = false
> ```

Hello, thank you very much now it works perfectly!
